### ISSUE TITLE
more informative readme needed

### ISSUE THREAD

**Issue by holgerbrandl** [HanSolo/charts#1]
E.g. could you provide some screenshots about provided chart widgets?

**Comment by thomasnield** [comment]
@holgerbrandl I will look into documenting this shortly while Gerrit works on the implementation. We are still in early stages but I think this is showing a lot of promise already.

**Comment by HanSolo** [comment]
At the moment the whole thing is work in progress and things are changing on a daily base. There will be screenshots and documentation as soon as it will be in a more stable state. Thx for the feedback.

**Comment by thomasnield** [comment]
I'm going to set aside some time to update the README again in a few days.
