### ISSUE TITLE
Parallel coordinates performance

### ISSUE THREAD

**Issue by antoine-guillou** [HanSolo/charts#10]
I tested the parallel coordinates charts, I really like it 👍 
However as soon as the data gets bigger the performance drops quickly. On my machine, more than 500 samples take several seconds to refresh.

I changed the way drawConnections works, by using Lines instead of Paths and it greatly improved the performance. Plotting 100000 samples with Lines takes roughly the same time as plotting 500 samples with Paths.

I'll submit a pull request with this change.

**Comment by HanSolo** [comment]
I’ve included your MR in one of my commits, thx
