### ISSUE TITLE
Where can I find tutorials to learn how to work with this library

### ISSUE THREAD

**Issue by Mohammed-Ryiad-Eiadeh** [HanSolo/charts#106]
How to work with this library and where are the tutorials?

**Comment by HanSolo** [comment]
There are no tutorials because this is a fun side project of mine. If you would like to see how to use the charts you might want to take a look at the test package of this lib, it contains a test file for each chart.

**Comment by Mohammed-Ryiad-Eiadeh** [comment]
Amazing, thank you so much.
