### ISSUE TITLE
MatrixBuilder is very slow

### ISSUE THREAD

**Issue by ennioVisco** [HanSolo/charts#108]
Hello,

I wanted to share my use case, as perhaps it can help in addressing some performance issues.
I'm currently using this library to draw a matrix heatmap overlay over a picture. 
The picture of interest, in my case, is a screenshot, and therefore the heatmap can be as granular as the pixels of the picture.

The problem is that this makes the drawing process extremely slow. In my experiments, it takes as much as 1 min and a half to compute the heatmap matrix, while the screenshot is taken in a matter of seconds. 

Am I doing something wrong, or there is objectively some issue with the chart? Note also that in my case the heatmap only has two colors, so spending such a big time to compute it is quite frustrating :/

**Comment by HanSolo** [comment]
Hi there, could you create a code snippet that demonstrate the problem so that I can reproduce it?

**Comment by ennioVisco** [comment]
> Hi there, could you create a code snippet that demonstrate the problem so that I can reproduce it?

Sure, I can work on that! Do you have some toy examples? It would be easy to start from there than from my current usage.
Note that my point is very simple, I really mean making a grid of 1920x1080, or something like that :)

**Comment by ennioVisco** [comment]
It turns out it was not an issue of the method, but rather a misconfiguration of the JavaFX routine I was using. Closing it :)
