### ISSUE TITLE
This entire project is a rat nest

### ISSUE THREAD

**Issue by krebznet** [HanSolo/charts#129]
Man I appreciate the code, but none of your stuff builds out of the box, you have multiple complex dependency chains.  I just hacked at your demo for about an hour, got some of it to run multiple modules have multiple versions like geo Line, Country, just take it off the Internet and do the public a favor.

**Comment by HanSolo** [comment]
I’m sorry that you are not able to run it, seems to work for all others. Why don’t you write your own stuff instead of blaming others…?
