### ISSUE TITLE
Request to add box-plot

### ISSUE THREAD

**Issue by adn4n** [HanSolo/charts#16]
Great work guys, much appreciated. I was wondering if it would be possible to add a neat box-plot in this collection? 
Here are a couple of examples from d3.js:
 1) https://observablehq.com/@d3/box-plot
 2) http://bl.ocks.org/jensgrubert/7789216

I think, similar to the first example, the ability to overlay all data points and then selecting and filtering some of these (e.g., outliers or from a certain quartile) would be amazing.

**Comment by HanSolo** [comment]
I know it's a very late reply but I simply did not have the time to implement it. This does not mean that it won't happen, I just need to find some time...sorry.

**Comment by HanSolo** [comment]
I know it's late but I finally was able to add a BoxPlot to the jdk17 branch with commit: e239cbc7b3db16302b5cf3be6268e6992f2907aa
