### ISSUE TITLE
Add ability to be used in Scenebuilder

### ISSUE THREAD

**Issue by icojb25** [HanSolo/charts#20]
These are great charts (and of course, thank you very much for your effort), is it possible to add whatever is required to use these in FXML layouts / Scenebuilder

**Comment by HanSolo** [comment]
To be honest I never tried it. You have to add the jr file to SceneBuilder and then you should be able to use it in SceneBuilder.

**Comment by HanSolo** [comment]
I've just made a quick test in SceneBuilder by adding the charts.jar as an external library from the file system and I can add things like a CircularPlot etc. 
So you should be able to use it as it is.
