### ISSUE TITLE
Set different Color for Outgoings than PlotItem in CircularPlot

### ISSUE THREAD

**Issue by Pureandy** [HanSolo/charts#21]
Hello Gerrit,

Thanks for all your work you put in your Liberies.
I would like to know if it's possible to set a different Color for the outgoings as for the PlotItems in the CircularPlot.

**Comment by HanSolo** [comment]
Would it be possible to add a little sketch that shows how the result should look like as an example?

**Comment by Pureandy** [comment]
Sure,
Example1 shows the normal behavior with a green Color for the connection because the node Europa is green.
![example1](https://user-images.githubusercontent.com/6490663/91275544-9d5a6a80-e780-11ea-9eb8-ef2e0a38b595.png)
Example2 shows the behavior I would like to get. Where the connection has a different Color than the node.
![example2](https://user-images.githubusercontent.com/6490663/91275567-a3e8e200-e780-11ea-8c4b-469eea8f3265.png)

**Comment by HanSolo** [comment]
Ok, in this case I got it right. Added a Connection class yesterday that makes it possible to set a color for specific connection. You can find a working version in the CircularPlotTest class (The blue connection in the screenshot).
![Circular Plot 2020-08-26 11-15-33](https://user-images.githubusercontent.com/62843/91285803-ecf36300-e78d-11ea-9dd6-4d033ca35fc9.png)

**Comment by Pureandy** [comment]
This is exactly what I was looking for. Thank you very much

**Comment by HanSolo** [comment]
Perfect :)
