### ISSUE TITLE
CircularPlot: Connection fill Color

### ISSUE THREAD

**Issue by Pureandy** [HanSolo/charts#24]
Hello Gerrit,

I know I allready asked for this and you implemented it because of me, but I have a slight problem with it.
When I try to change the color of the Connections, it only allows it for max. 1 Connection per PlotItem its coming from.
So if I have 2 Connections going from X to Y and from X to Z, I can only decide the color of one of those.
The other Connection will have the color of the PlotItem.
My wish would be to change the color of all Connections.

It would also be very helpful if the Connection would hold the value it has.
At this moment it only has incoming, outgoing and the color.

Thanks in advance :)

**Comment by HanSolo** [comment]
Ok, I will take a look at it...

**Comment by HanSolo** [comment]
Hi there, so I've added ConnectionEvent and ConnectionListener which makes it possible to receive events when you click on a connection.
If you take a look at the CircularPlotTest class you will see how to add a listener to each connection and handle those events. In this class you will also find the way how to set different colors for different connections, so it works on my machine.
Please let me know if that fixes your problem.
Cheers, Gerrit

**Comment by Pureandy** [comment]
That fixes my problem, thanks alot.

**Comment by HanSolo** [comment]
Ok cool, so please let me know when you have other things you need. If you think you can work with the features available, let me know and I will create another release.

**Comment by Pureandy** [comment]
I Think I got everything I need now, you can create a new release. Thank you very much.

**Comment by HanSolo** [comment]
Release 11.3 is on it's way...might take some time before it will appear on Maven central...
