### ISSUE TITLE
Trouble understandig the usage

### ISSUE THREAD

**Issue by jkrude** [HanSolo/charts#27]
Hi first of all great work!
I am not too familiar with Java9 modules, but if` eu.hansolo.fx.charts.data` is not exported how can one create the necessary data-structure (e.g. a tree with TreeNode and ChartData) required for the chart (e.g. SunburstBuilder.setTree)?

**Comment by HanSolo** [comment]
Ups...did I forgot to export it...will take a look at it...thx for the heads up 👍🏻

**Comment by HanSolo** [comment]
Fixed with commit 831223d2206e343390ab660440e94b9de789832d
