### ISSUE TITLE
Update Problem with Maven

### ISSUE THREAD

**Issue by Pureandy** [HanSolo/charts#28]
Hello Gerrit,

with the new Release there is a Problem with the download via Maven Update.
![Files](https://user-images.githubusercontent.com/6490663/96690573-24445180-1384-11eb-84e8-82df81e9af92.png)
I and others that I asked can only download the .lastUpdated Files.
From what I can tell that means that the download was unsuccessful.

Maybe you know how to solve this problem.

**Comment by HanSolo** [comment]
Hmmm...strange...will take a look at that, thx for the heads up

**Comment by Pureandy** [comment]
Not sure if you changed anything, but after another time of deleting the .lastUpdated Files and another MavenUpdate it works now.
