### ISSUE TITLE
Flow Circle

### ISSUE THREAD

**Issue by thomasnield** [HanSolo/charts#3]
No pressure Gerrit, I showed my coworkers some of your work. One of them has asked if creating a flow circle graph is doable. This is something that would be really killer for connection-driven flow problems (e.g. transportation, trade economics, etc). 

What do you think? 

![image](https://user-images.githubusercontent.com/7420801/32800321-99a94062-c93f-11e7-940f-006db69dfcb9.png)

**Comment by HanSolo** [comment]
Yep should be possible. It would be nice if you could provide some data to create such a chart.

**Comment by thomasnield** [comment]
I'll put something together.

**Comment by HanSolo** [comment]
Awesome...👍🏻

**Comment by thomasnield** [comment]
Here's a start. 


REGION1 | REGION2 | WEIGHT
-- | -- | --
Dallas | Phoenix | 0.2
Dallas | Chicago | 0.4
Dallas | Austin | 0.3
Dallas | Albuquerque | 0.1
Phoenix | Chicago | 0.4
Phoenix | Austin | 0.2
Austin | Chicago | 0.1
Austin | Albuquerque | 0.4
Albuquerque | Phoenix | 0.5

I envision the API will allow user to establish arbitrary relationships between any two `T` items with a weight. The hashcode/equals implementation of each `T` item will trigger a lookup to see if each `T` item exists already, and then establish the weighted relationship with the other item. 

I imagine the onus will be on the user to input the correct weights ahead of time. I suppose the weights don't have to add up to 1 for each `T` item. 

```java
FlowCircleModel model = new FlowCircleModel();

List<WeightedCityPair> weightedCityPairs = ...;

for (wcp: weightedCityPairs) { 
	model.add(wcp.getCity1(), wcp.getCity2(), wcp.getWeight());
}
```

**Comment by thomasnield** [comment]
I looked at a few examples of this chart, and it looks like for a given pair of items A and B, the weight is the same for AB and BA. Direction has no impact, and the length of each ribbon tail is the same on both ends. 

Here's a somewhat helpful description.
https://www.r-bloggers.com/circular-migration-flow-plots-in-r/

**Comment by HanSolo** [comment]
Made some first tests and it looks promising so far...
<img width="872" alt="circularplot" src="https://user-images.githubusercontent.com/62843/32989450-77bb9e5c-cd16-11e7-9040-8058be8674d1.png">

**Comment by thomasnield** [comment]
@HanSolo oh my gosh this is awesome! I'm so going to play with this! Thanks Gerrit!

**Comment by thomasnield** [comment]
I'm kind of second-guessing what I proposed with the data strucuture. Maybe the tails should be allowed to have different widths on either end, meaning that two values should be associated with each pair possibly...

**Comment by HanSolo** [comment]
So at the moment this is not possible. I've took a look at different circular plots and in most of them the plot was used to visualize some kind of flow from one section to another. In my current implementation you define the chart items with their values. Then you can add outgoing connections to each chart item with a value. With this approach I've created a chart that visualizes the results of the current election in Germany with each party and it's end result and with the flow of voters from each party to the other parties. The election plot is based on real data. It's a really interesting approach to visualize data. 
The second plot shows some fictive data of travellers between countries. So for example it shows how many people traveled from Australia to India, China, Japan, Thailand and Singapore. The value of each segment is the number of all travellers for that country.
Here are the two plots...
<img width="1043" alt="circularplot" src="https://user-images.githubusercontent.com/62843/33026662-37cb35fe-ce11-11e7-8989-e1a794786c0d.png">

**Comment by thomasnield** [comment]
Okay this makes sense. Really interesting examples you whipped up too.  I guess my remaining question is this: is it possible to represent flow in both directions for each item? Can I show movement of UNION -> FDP as well as FDP -> UNION? Or does that not make sense for what this graph conventionally achieves?

**Comment by HanSolo** [comment]
Yep that's possible as you can see in the travel example. There are flows from China to Japan and vice versa. First I've implemented something like incoming and outgoing before I realized that you only need an outgoing property. To pick up your example the code would like like this:
```Java
union.addToOutgoing(fdp, 1_360_000);
fdp.addToOutgoing(union, 500_000);
```

**Comment by HanSolo** [comment]
I've committed already locally and will push the stuff to the repo after I have made some more tests tomorrow morning...only have the early morning hours :)

**Comment by HanSolo** [comment]
Added the circular plot to the chart lib...

**Comment by thomasnield** [comment]
Awesome, I'll play with this today!

**Comment by thomasnield** [comment]
Love it, this is perfect :D
