### ISSUE TITLE
SelectionEvent support for SankeyPlot

### ISSUE THREAD

**Issue by cseeberg** [HanSolo/charts#30]
Hi Gerrit!

Could you please implement a SelectionEvent for the SankeyPlot chart (like you've done for the ArcChart) so that when the user clicks a on the chart connections (or endpoints) then the event would contain the in/out connection ?

Best regards and keep up the great work !
Carstein

**Comment by HanSolo** [comment]
Will try to implement that asap...

**Comment by HanSolo** [comment]
Could you check the current implementation in the dev branch? In the SankeyPlotTest I've replaced the tooltips by events which contains the source and target item. With this you can get the value by source.getOutgoing().get(target).
In addition one can set the selection color in sankey plot which will highlight the selected connection. Please let me know if this works for you.

**Comment by cseeberg** [comment]
Thanks, this will work.

**Comment by cseeberg** [comment]
I pulled the dev branch and did a build.  I now see the selected source/target being selected (color change), but I do not get the fired event.  See snippet below:
`sankeyPlot.getItems().forEach(item -> item.setOnItemEvent (e->{
				if (e.getEventType() == EventType.SELECTED)
				{
			    	PlotItem srcItem = (PlotItem) e.getItem();
                	PlotItem targetItem = (PlotItem) e.getTargetItem();
                	logger.info("SankeyPlot: selection src="+srcItem.getName()+", target="+targetItem.getName());
                	setFilterPredicate(srcItem.getName(),targetItem.getName(),null);					
				}
			}));
`

**Comment by HanSolo** [comment]
If you take a look at the SankeyPlotTest code you will see how to get the events. The output on the console in the demo does exactly the same.

**Comment by HanSolo** [comment]
Oh I just see that you do that already 😁  Need to check.

**Comment by HanSolo** [comment]
You did add the items before you add the listeners right?

**Comment by cseeberg** [comment]
Yes it’s exactly the same code as for the arcChart which works

Sent from my iPhone...

**Comment by HanSolo** [comment]
Could you create a gist that shows the problem so that I can easily reproduce?

**Comment by cseeberg** [comment]
Ooops, my bad.
I had 2 places in my code where I tested out the sankeyPlot.  It works like
a charm my friend, sorry about that :-)


man. 7. des. 2020 kl. 20:18 skrev Gerrit Grunwald <notifications@github.com

**Comment by HanSolo** [comment]
Ah ok...cool 😁👍🏻

**Comment by HanSolo** [comment]
Fixed with release 11.6
