### ISSUE TITLE
Bugs and improvements for the SunburstChart

### ISSUE THREAD

**Issue by jkrude** [HanSolo/charts#32]
### Bug in SunburstChart:
_Occurs_ if there is only one node in the first-level (below root) whose value is != 0.
_Effect_: Segment missing (if interactive). Segment to big(if not interactive and no further child nodes != 0)
Currently, whole circles cannot be drawn because (in this instance) x2 and x3 are equal in `createSegment`. I guess this happens because `startAngleRad == 0` and `endAngleRad == 2pi`, but` sin(0) = 0 ==sin(2pi)`

### Further improvements:
- only redraw on `TreeNodeEvents` if the type is not `SELECTED`
- currently the chart is drawn 9 times for the default example, because after every attribute change an event-handler is triggered. This could be avoided by some extra code in the builder class
- register listener for the node values and redraw on change
- - something like: `tree.stream().forEach(tTreeNode -> tTreeNode.getItem().valueProperty().addListener((observable -> redraw())));`
- let users decide what tooltip to display on segments

**Comment by jkrude** [comment]
I am happy implementing some of those changes, but would like to hear your opinion first (on how and what)

**Comment by HanSolo** [comment]
Because I myself don't use the charts but only created them for the fun of it, feel free to submit merge requests if you think it really makes sense also for others. No problem at all... :)
