### ISSUE TITLE
Choose fonts and color for the description of PlotItems in a Circular chart

### ISSUE THREAD

**Issue by Pureandy** [HanSolo/charts#34]
Hello Gerrit,

Is it possible to choose the color and/or the font for the description of the PlotItems in a Circular chart?
Here is an example:
![Example](https://user-images.githubusercontent.com/6490663/112611454-21abc380-8e1e-11eb-8273-ad8b41658572.png)
I would like to choose color and font for the names (Australia, India, China, etc...) as well as for the Tick marks and Tick mark labels.

Is there currently a way to do this?

**Comment by HanSolo** [comment]
Hi there, not at the moment but I can take a look at it.

**Comment by HanSolo** [comment]
Implemented in jdk16 branch with commit hash 2cf11cdff3c6bcfb8b2ef3730e43b687d2a33984
