### ISSUE TITLE
Usage Instructions

### ISSUE THREAD

**Issue by kqtrinh** [HanSolo/charts#40]
Hi To the HanSolo Charts Developers,

I am interested experiment with your library of plots the polar and the radar plots in particular. I am quite new to Java. I tried to best to update my Java development environment to OpenJDK16 with javaFX-sdk-16. Latest Eclipse Oomph and grade 7.1.1 to try to run the radar chart test application. I messed with with on the fly when running into problems and trying to solve it by googling.

Had spent ~1 day on it without any luck to get the test application working. I am at a point where at least entire project is imported into Eclipse and the the radar test application is no longer showing a bunch of red lines. When run, I encountered below error:

WARNING: Unknown module: charts specified to --patch-module
Error: Could not find or load main class eu.hansolo.fx.charts.RadarChartTest
Caused by: java.lang.ClassNotFoundException: eu.hansolo.fx.charts.RadarChartTest

Also tried googling for a solution but I got no where so far.

Your vast supported plots are so valuable for the scientific community. I am wondering if there is any  documentation to guide one to at least get pass the setting up of development environment (the basic toolchain required to run/develop with your library) so one can develop their FX app to consume your library.

Any help would be greatly appreciated in this regards,
Thanks,

**Comment by HanSolo** [comment]
Hi there, the charts library doesn‘t need anything special, but just a working Java+JavaFX environment. You could either use the master branch with JDK11+JavaFX11 or the jdk16 branch with JDK16+JavaFX16. To set up the environment just follow the instructions on openjfx.io. When the environment is setup correctly you could run the selected chart by starting the specific launcher class. For each chart there should be a launcher and a test class. The test class contains the code that shows how to use the selected chart.
