### ISSUE TITLE
Error While Importing Branch JDK16 Into Eclipse

### ISSUE THREAD

**Issue by kqtrinh** [HanSolo/charts#42]
I tried to import charts as a Gradle Project into Eclipse with error. 
Please see attached screenshot for the error.
Thanks,

![Capture](https://user-images.githubusercontent.com/13751693/124516516-ac457c80-dd96-11eb-8bfe-d5fd32ea9b71.JPG)

**Comment by HanSolo** [comment]
Looks like your environment is not setup correctly.
