### ISSUE TITLE
Add a Parallel Coordinates Plot

### ISSUE THREAD

**Issue by Groostav** [HanSolo/charts#5]
I've got a _crippling_ need for a Parallel Coordinates plot on our JavaFX/TornadoFX desktop application.

Parallel Coordinates Plots (PCPs) are a very simple abstraction on a standard many-column matrix. A PCP graphs each row in the table as a horizontal line across the chart. Each column is represented as a vertical axies, and where that axis intersects each horizontal line, the height of the intersection from the bottom fo the chart is proportional to that rows value at that column.

A picture is worth a thousand words:

Our applications Parallel Coordinates chart:
![image](https://user-images.githubusercontent.com/1680611/33501759-9a23db32-d692-11e7-9895-bf1480dcb329.png)

The corresponding Matrix:
![image](https://user-images.githubusercontent.com/1680611/33501774-ab8310f0-d692-11e7-971f-71c6e14f0c7e.png)

a D3JS implementation:
https://bl.ocks.org/jasondavies/1341281

Parallel Coordintes represents a superbly general chart _as it allows you to graphically represent data at arbitrarily high dimensionality_.

There is a long list of features such a chart might have, which I'll outline below.

Our implementation is not worth sharing primarily because its use of bindings is ~~inefficient~~ **abusive**. We write an optimization algorithm which can redline the CPU for prolonged periods of time, but in many cases our profiling has indicated _that the actual problematic hot loop is binding updates for our PCP implementation_. Thus we would very much like another one, but we simply cant afford the time it would take to re-write it.

---

shameless plug: find out more about this product at [empowerops.com](http://empowerops.com)

**Comment by thomasnield** [comment]
So it's like a simplified Sankey plot with non-weighted lines? Can you outline a minimum set of features you would like to see? 

I won't speak for Gerrit, but the scope of this project will likely succeed on simple, elegant API's. Gerrit's mathematical sorcery does all the work in making an optimal layout for the charts. Therefore, let's start with a minimalist set of features if that's possible.

**Comment by Groostav** [comment]
## Nice-to-have 1: Highlighted-filters ##

filtering on axies: when you click and drag down on an axies, the plot should highlight the points covered by your dragging motion:

![image](https://user-images.githubusercontent.com/1680611/33502100-ad7f4f44-d693-11e7-8148-4d4dde2310a6.png)

our application used to have this, but we ditched it because we couldn't quite get a nice behavior around dragging-and-releasing on an axis, with the listener approach we had. Nor was it fast.

## Nice-to-have 2: Banding support ##

Support for pluggable clustering behaviour:

![image](https://user-images.githubusercontent.com/1680611/33502170-e9711604-d693-11e7-906d-12e1397edff2.png)

Our applications logic will bin/cluster points as it sees fit. It would be nice to be able to draw not only individual points, but also "clusters" as bands. Ideally we'd like to render both the cluster _and the individual members in the cluster_ in some kind of elegant way.

I'd also like the opposite behaviour.

In this sense, an `ObservableList<Row>` with a bi-directional binding would likely be the most expressive way to ask for this.

## Nice-to-have 3: "Brushing" ##

some kind of selection-event, such that when I select some rows in a different view, _like shift-clicking some rows in my table-view_....

![image](https://user-images.githubusercontent.com/1680611/33502242-331b3550-d694-11e7-992a-cb5af905a64e.png)

I get a corresponding selection of those points in PCP...

![image](https://user-images.githubusercontent.com/1680611/33502261-3e2997ca-d694-11e7-9bcb-cf809e1a0355.png)

## Nice-to-have 4: scrolling ##

I mentioned _arbitrarily high numbers of dimensions_, meaning we need to be able to render data at up-to 100 columns. You cannot feasibly fit 100 colums on most screens, so the ability to elegantly scroll through them would be nice. This can likely be left to a scroll-pane or other more systems device, but the preferred/min/max size behaviour of this component would need to be proper:

![image](https://user-images.githubusercontent.com/1680611/33502406-c9cc9502-d694-11e7-889c-46c7a45d4df3.png)

**Comment by HanSolo** [comment]
Hmm...that chart looks neat...this one might take a bit longer to implement but I think I‘ll give it a try. Like it :)

**Comment by Groostav** [comment]
>I won't speak for Gerrit, but the scope of this project will likely succeed on simple, elegant API's. Gerrit's mathematical sorcery does all the work in making an optimal layout for the charts. Therefore, let's start with a minimalist set of features if that's possible.
>
>Hmm...that chart looks neat...this one might take a bit longer to implement but I think I‘ll give it a try. Like it :)

You guys have made me a happy camper.

**Comment by HanSolo** [comment]
As I see it right now the main problem won‘t be the chart itself but to find a neat way to handle the data...need to think about it...

**Comment by thomasnield** [comment]
@Groostav see my note above ^^. Again, please try to minimize the scope of this as much as possible for a minimum viable product. 

If we make it too specific or too detailed (at least at first), it marginalizes its universal utility as an OSS project.

**Comment by Groostav** [comment]
>So it's like a simplified Sankey plot with non-weighted lines? Can you outline a minimum set of features you would like to see?

I mean, to my mind if I can take a TableView's model (An observable list of JavaFX style POJO's, and Columns with "property factories" that convert a row to a cell value), and use that as this charts backing model, along with a strategy to render individual points on the chart, I'd be happy.

If you could retrofit a "composite-component" into the "rows", such that some rows produce maybe an `kotlin.ClosedRange` rather than an individual value, at that point you're pretty close to feature-parity with our chart.

Bolt on a `Selected` property, proper width/height behaviour for scrolling, and a filterint system, and you would have something that competes with the multitude of D3JS PCP implementations.

**Comment by Groostav** [comment]
see also: https://syntagmatic.github.io/parallel-coordinates/

They've got a "progressive rendering" mode on a PCP with many (millions?) of entries. I cant help but think this is a great place for some `suspend` fun's, but that might be bumping the complexity up too high.

**Comment by HanSolo** [comment]
So I've started implementing a Parallel Coordinates Chart and you will find a demo in the test package. At the moment I'm fine with it (cause I just have the evenings to work on that). I've implemented the mouse filtering. It's not perfect yet but it's a start...I think one could spend weeks on making this chart perfect :)

**Comment by Groostav** [comment]
That sample is [ParallelCoordinatesChartTest.java](../blob/master/src/test/java/eu/hansolo/fx/charts/ParallelCoordinatesChartTest.java), hoping to have some time today to check it out.
