### ISSUE TITLE
MatrixPane update on new data

### ISSUE THREAD

**Issue by permiakovsa** [HanSolo/charts#62]
I'm trying to use MaxtrixPane for incoming data, so I add new matrixItems in to the ArrayList<MatrixChartItem>, but the data won't appear.
This problem is resolving with redrawing matrix with recreating the MatrixPane.
Is it possible to redraw matrix on series change event?

**Comment by HanSolo** [comment]
I've added a ListChangeListener to the MatrixSeries items which will trigger a redraw on every change in branch jdk16 (commit hash: f90e93aacc5ab0c596fb8554a7e66d73a7f42008)
