### ISSUE TITLE
Pareto Chart

### ISSUE THREAD

**Issue by point85** [HanSolo/charts#7]
Do you have any plans to create a Pareto Chart?  This is a very common bar chart used in industry to plot the N largest items by count or percentage decreasing left to right.  A line chart showing cumulative values is superimposed on the bar chart thus increasing left to right.  Clicking on a bar provides an event for "drilling down" into more detail.

**Comment by HanSolo** [comment]
Definitely interesting so I will take a closer look to it. Thank's for mentioning it, really appreciated :)

**Comment by point85** [comment]
Thanks for considering the Pareto chart.  I have attached a screen shot
from the current state of development of my Overall Equipment Effectiveness
(OEE) dashboard.  I have used four of your tiles for the OEE metrics above
the Pareto chart.  I made the Pareto chart by overlaying a line and bar
chart.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by HanSolo** [comment]
I know it is late but better than late than never, now you can find a pareto chart in the lib.

**Comment by point85** [comment]
Great thanks Gerrit. I will check it out!

**Comment by point85** [comment]
This is very nice work!  My only feedback would be to consider an option to
plot the Y-axis values as a percentage (see attached chart) instead of
absolute values.

**Comment by HanSolo** [comment]
Ok will take a look at it.

**Comment by point85** [comment]
And one more thing -- Can I add a click listener to a Pareto bar or dot to
detect this event?
