### ISSUE TITLE
Gradle build problem

### ISSUE THREAD

**Issue by NeptuneTheMystic** [HanSolo/charts#71]
Hello,

I'm not too familiar with gradle and this is the first time I've attempted download and check out the charts library.  If I'm not mistaken, in order to run the demo (Debian Bullseye), I should:

`./gradlew demo`

But when doing so, I get the following.  Is it enough to help determine the problem?  Thanks in advance.

Configure project :
Project : => 'eu.hansolo.fx.charts' Java module

FAILURE: Build failed with an exception.

Where:
Build file '/testdir/charts-17.1.2/build.gradle' line: 149

What went wrong:
A problem occurred evaluating root project 'charts'.
Could not get unknown property 'ossrhUsername' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.

**Comment by HanSolo** [comment]
Oh there is indeed a problem in the build file that I did not recognize because the missing env variables are set on my machine. Will fix it asap, thx for the hint 👍🏻

**Comment by HanSolo** [comment]
I just took a short look at the files and saw that I removed the Demo task from the gradle file. Because there is not one Demo file any more (because of too many different charts) I would suggest to download the source code and run the test for the chart you are interested in, in your IDE. For example if you would like to run the CircularPlot, you need to execute the CircularPlotTestLauncher in the test packages.

**Comment by NeptuneTheMystic** [comment]
Hi Gerrit,

I was hoping to just quickly check out the sunburst chart, but after adding the charts project to Eclipse, it wasn't happy because it was missing module dependencies.

After spending a couple of hours cloning, importing and configuring toolbox, toolboxfx, jdktools, heatmap, and countries, I've swung back around to charts and it is giving me two problems that I can't resolve; I suspect they may involve missing file commits but I'm not sure.

Both errors are within en.hansolo.fx.charts:

  BubbleGridChart.java, line 125: no reference to the Bubble class
  
  SectorChart.java, line 86: no reference to the Sector class

I'm looking forward to checking all this out - I'm close!  Just need to resolve those errors.

**Comment by HanSolo** [comment]
To solve such problems in the future I've created a little getting started project that you can find [here](https://github.com/HanSolo/gettingstarted). This shows how to use Charts and TilesFX with JDK17. I hope it will help you...

**Comment by NeptuneTheMystic** [comment]
Gerrit, thank you for taking the time to do that.  The projects do indeed run.  It took me a couple of hours because of being unfamiliar with gradle, mixing up JDK 11 & JDK 17, and an incorrect JAVA_HOME environment variable.  Egads - it was nothing you did, just my system not being up to date.

In regards to the projects loaded into Eclipse, I'll tell you that I was basically doing everything wrong that I possibly could!  I've got it all sorted out now, and all of the projects compile without errors (I was also lacking JDK 17 prior).

I just need to get an issue sorted with the class path so the demo project launchers run and I'll be on my way.  Hopefully I'll have some time this weekend to tinker with it.

**Comment by HanSolo** [comment]
Glad it works now 👍🏻
