### ISSUE TITLE
request to add  candle chart

### ISSUE THREAD

**Issue by Xiaobaishushu25** [HanSolo/charts#83]
You are excellent. These charts are very beautiful, but I want to ask if it is possible to add a candle chart, which is the K-line chart of stocks. Thank you!

**Comment by HanSolo** [comment]
I guess the data that will be provided contains high, low, open, close and a timestamp right? And then you will need a time based series of these datapoints to be able to visualize it. Should not be too hard to implement, just need to find some time… 😁

**Comment by Xiaobaishushu25** [comment]
> 

yes,That's what I want. It's better to add a tooltip to display relevant information when the mouse is hovering. I'm a novice in JavaFX and can't realize the chart by myself... Thank you for your efforts！

**Comment by HanSolo** [comment]
Added CandleChart in jdk17 branch with commit fbb0a5534e25956854af56ed75790c5e4a9f1b24
