### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Xiaobaishushu25** [HanSolo/charts#84]

**Comment by Xiaobaishushu25** [comment]
Hello, thank you for your work. I am the person who requested to add a candle chart a few days ago. Now I know how to draw the main body of the candle chart, but I want to add moving average data (MA5、MA10). I found your smoothed line chart chart. I think this method draws a smooth curve
```
`  private void drawSmoothLine(XYSeries<T> SERIES, boolean SHOW_POINTS) {
        if (SERIES.isVisible()) {
            double LOWER_BOUND_X = this.getLowerBoundX();
            double LOWER_BOUND_Y = this.getLowerBoundY();
            this.ctx.setLineWidth(SERIES.getStrokeWidth() > -1.0 ? SERIES.getStrokeWidth() : this.size * 0.0025);
            this.ctx.setStroke(SERIES.getStroke());
            this.ctx.setFill(Color.TRANSPARENT);
            List<Point> points = new ArrayList(SERIES.getItems().size());
            SERIES.getItems().forEach((item) -> {
                points.add(new Point(item.getX(), item.getY(), item.isEmptyItem()));
            });
            Point[] interpolatedPoints = Helper.subdividePoints((Point[])points.toArray(new Point[0]), 24);
            this.ctx.beginPath();
            Point[] var9 = interpolatedPoints;
            int var10 = interpolatedPoints.length;

            for(int var11 = 0; var11 < var10; ++var11) {
                Point p = var9[var11];
                if (p.isEmpty()) {
                    this.ctx.moveTo((p.getX() - LOWER_BOUND_X) * this.scaleX, this.height - (p.getY() - LOWER_BOUND_Y) * this.scaleY);
                } else {
                    this.ctx.lineTo((p.getX() - LOWER_BOUND_X) * this.scaleX, this.height - (p.getY() - LOWER_BOUND_Y) * this.scaleY);
                }
            }

            this.ctx.stroke();
            if (SHOW_POINTS) {
                this.drawSymbols(SERIES);
            }

        }
    }`
```
 but I don't understand how he draws the curve. I try to draw it with beginpath(), moveto (x, y), lineto (x, y) and stroke(), But I can only get the line chart with sharp corners, so can you explain it,Or there are better suggestions for adding moving averages in the candle chart. Thank you!

**Comment by HanSolo** [comment]
Understand, let me add something to the demo. Btw, do you have an example dataset that I can use?

**Comment by Xiaobaishushu25** [comment]
> Understand, let me add something to the demo. Btw, do you have an example dataset that I can use?
Thank you for your timely reply, but I originally intended to figure out how to draw and then read the data from the database, so I'm sorry I don't know how to provide you with the dataset...
And also i think there is a small bug in the CandleChart,please  observe the picture，the item data both high and low are around 35, but the scale on the left is about 43

![image](https://user-images.githubusercontent.com/76581880/184128666-fc490afe-25ea-4a31-b7b3-89390a32a098.png)

**Comment by HanSolo** [comment]
Understand, let me add something to the demo. Btw, do you have an example dataset that I can use?

**Comment by Xiaobaishushu25** [comment]
I don't know how to send you a data set, nor what form you need, so I uploaded a data set you can download in my GitHub repository Dataset, which contains some data. Each row is：${s.name} ${s.date} ${s.low} ${s.open} ${s.close} ${s.high} ${s.MA5} ${s.MA10} ${s.MA20} ${s.MA60} ，I think you can understand the data. i dont know that data is right?

**Comment by HanSolo** [comment]
Ok thx. The problem with the axis is related to the fact that I construct the chart manually, will fix that too.

**Comment by HanSolo** [comment]
If you check out the latest commit from JDK17 branch you should now see your data incl. ma5, ma10, ma20 and ma60. Please let me know if that looks good to you...

**Comment by Xiaobaishushu25** [comment]
ok，the new CandleChart is very nice，That's what I need ，thank you very much！！

**Comment by HanSolo** [comment]
Glad it works for you. Will create a new release of charts that contains the code later today.
