### ISSUE TITLE
eu.hansolo.fx:charts:17.1.21 no longer found in maven central?

### ISSUE THREAD

**Issue by ThomasDaheim** [HanSolo/charts#85]
Hi,

I have added eu.hansolo.fx:charts:17.1.21 just a few days ago in my build.gradle and it worked fine. But when I'm checking maven now, there are no more versions 17.* available and the only one is [11.0](https://mvnrepository.com/artifact/eu.hansolo.fx.charts/charts/11.0)? E.g. heatmap is still there in versions 17.0.

Maybe its just too late for me today...

**Comment by HanSolo** [comment]
If I look here: https://search.maven.org/artifact/eu.hansolo.fx/charts they are all there and it also works in my own apps where I use the charts

**Comment by ThomasDaheim** [comment]
Works like a charm today. Glitch in the matrix?

Have a great weekend!
