### ISSUE TITLE
Axis title font size is not working

### ISSUE THREAD

**Issue by permiakovsa** [HanSolo/charts#90]
via `AxisBuilder.create(..)` ` .titleFontSize() ` does not change size of title

**Comment by HanSolo** [comment]
Fixed the issue with commit 30f1c529b9a95077137b9e0be5e84b50670189c9
You can now switch of the automatic font size calculation of the axis title by calling .autoTitleFontSize(false) in the AxisBuilder or setAutoTitleFontSize(false). In this case it will take the value that you can set with .titleFontSize(NN).
