### ISSUE TITLE
Updating Axis range in LineChart

### ISSUE THREAD

**Issue by permiakovsa** [HanSolo/charts#91]
via setting minValue or/and maxValue at axis, axis stays at the same range. but if drag the application window - it will be updated and apply new values

**Comment by permiakovsa** [comment]
i think the calling on `redraw()` of Axis will fix this, but is private

**Comment by HanSolo** [comment]
Fixed issue with commit 4882f06445fd017b830c349baf354c0a7a5930ed
It's in the jdk17 branch of the project and you might want to check it out to avoid reflection

**Comment by permiakovsa** [comment]
hi again! 
 the problem is little bit more complex
here - there is initial state of chart and Y-range is -50..50
![изображение](https://user-images.githubusercontent.com/42047797/190996882-594628ad-dab8-4f65-9313-ae99a5069e3c.png)
then switch to -10..10
![изображение](https://user-images.githubusercontent.com/42047797/190997101-4fc11698-a08d-42e3-aeec-8fbf65e90a3d.png)
and finally to -150..150
![изображение](https://user-images.githubusercontent.com/42047797/190997168-6cf82ccd-ff60-4865-954e-8e8624c015d4.png)

as you see we need to adjustChartRange() and adjust grid

**Comment by HanSolo** [comment]
Maybe it's a good idea to provide a simple example that shows the problem, otherwise it just takes longer trying to reproduce your exact issue.

**Comment by permiakovsa** [comment]
sure i will prepair a simple project. on my way!

**Comment by HanSolo** [comment]
I think it's already fixed with commit: 92a284e9f29a410c3ca1a741f7e4e68e385c5468
Can you give it a try please ?

**Comment by permiakovsa** [comment]
I'm not sure how to try the commit, because all project git clone fails with gradle issues - kinda like 'ossrhUsername' for Credentials [username: null]"
but from code this is exactly the thing

**Comment by HanSolo** [comment]
Oh...that's unfortunate, well I've tested it using the GridTest class in the test package and it does what you expected.

**Comment by HanSolo** [comment]
Released 17.1.25 to Maven central but might take a bit before it will show up...

**Comment by permiakovsa** [comment]
yes, it is brilliant!

**Comment by HanSolo** [comment]
Glad it works as expected 👍🏻
